parameters:
    applications:
        mapbender_user_wmc:
            title: Mapbender Demo Map WMC
            screenshot: 
            description: Fullscreen style, Simple map showing WMS use.
            published: true
            template:  Mapbender\CoreBundle\Template\Fullscreen
            regionProperties:
              - name: sidepane
                properties:
                  name: accordion
                  label: mb.manager.template.region.accordion.label
            layersets:
                main:
                    mapbender_users:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: Mapbender Users
                        url: https://wms.wheregroup.com/cgi-bin/mapbender_user.xml
                        version: 1.3.0
                        layers:
                            10: { name: Mapbender_User,    title : User, visible: true, legendurl: https://wms.wheregroup.com/cgi-bin/mapbender_user.xml?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=Mapbender_User&format=image/png&STYLE=default }
                            22: { name: Mapbender_Names,   title : Name, visible: true, queryable: true}
                        info_format: text/html
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: false
                        opacity: 85
                    osm:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: OSM Demo
                        url: https://osm-demo.wheregroup.com/service
                        version: 1.3.0
                        layers:
                            30: { name: osm,    title : Germany OSM Demo WhereGroup,  visible: true }
                        info_format: text/html
                        visible: true
                        format: image/png
                        transparent: true
                        tiled: true
                        opacity: 100
                overview:
                    osm_overview:
                        class: Mapbender\WmsBundle\Entity\WmsInstance
                        title: OSM Demo
                        url: https://osm-demo.wheregroup.com/service
                        version: 1.3.0
                        layers:
                            40: { name: osm,    title : Germany OSM Demo WhereGroup,  visible: true }
                        tiled: false
                        format: image/png
                        transparent: true
                        visible: true
                        opacity: 100
            elements:
                toolbar:
                    layertree-button:
                        title: mb.core.layertree.class.title
                        tooltip: mb.core.layertree.class.title
                        class: Mapbender\CoreBundle\Element\Button
                        label: true
                        icon: iconLayertree
                        target: layertreedialog
                        action: open
                    fi-button:
                        title: mb.core.featureinfo.class.title
                        tooltip: mb.core.featureinfo.class.title
                        class: Mapbender\CoreBundle\Element\Button
                        icon: iconInfoActive
                        label: true
                        target: featureinfo
                        deactivate: deactivate
                        group: featureinfo
                    print-button:
                        title: mb.core.printclient.class.title
                        tooltip: mb.core.printclient.class.title
                        class: Mapbender\CoreBundle\Element\Button
                        label: true
                        icon: iconPrint
                        target: printclient
                        action: open
                    imageexport-button:
                        title: Image Export
                        tooltip: Image Export
                        class: Mapbender\CoreBundle\Element\Button
                        label: true
                        icon: iconImageExport
                        target: imageexport
                        action: open
                    legend-button:
                        title: mb.core.legend.class.title
                        tooltip: mb.core.legend.class.title
                        class: Mapbender\CoreBundle\Element\Button
                        label: true
                        target: legend
                        icon: iconLegend
                        action: open
                    wmsloader-button:
                        title: mb.wms.wmsloader.class.title
                        tooltip: mb.wms.wmsloader.class.description
                        class: Mapbender\CoreBundle\Element\Button
                        label: true
                        target: wmsloader
                        icon: iconWms
                        action: open
                    gps-button:
                        title: mb.core.gpsposition.class.title
                        tooltip: mb.core.gpsposition.class.description
                        class: Mapbender\CoreBundle\Element\GpsPosition
                        label: true
                        target: map
                        action: open
                    linerulerButton:
                        title: mb.core.ruler.tag.measure
                        tooltip: mb.core.ruler.tag.line
                        class: Mapbender\CoreBundle\Element\Button
                        icon: icon-line-ruler
                        label: true
                        target: lineruler
                        deactivate: deactivate
                        group: rulers
                    arearulerButton:
                        title: mb.core.ruler.tag.measure 
                        tooltip: mb.core.ruler.tag.area
                        class: Mapbender\CoreBundle\Element\Button
                        icon: icon-area-ruler
                        label: true
                        target: arearuler
                        deactivate: deactivate
                        group: rulers
                    about:
                        title: mb.core.aboutdialog.tag.about
                        tooltip: mb.core.aboutdialog.tag.about
                        icon: icon-about
                        label: true
                        class: Mapbender\CoreBundle\Element\AboutDialog
                    poiButton:
                        title: mb.core.poi.class.title
                        tooltip: mb.core.poi.class.description
                        class: Mapbender\CoreBundle\Element\Button
                        icon: iconPoi
                        label: true
                        target: poi
                    wmc-editor-button:
                        title: mb.wmc.wmceditor.class.title
                        tooltip: mb.wmc.wmceditor.class.title
                        class: Mapbender\CoreBundle\Element\Button
                        label: true
                        icon: iconWmcEditor
                        target: wmceditor
                        action: activate
                    wmc-loader-button:
                        title: mb.wmc.wmcloader.class.title
                        tooltip: mb.wmc.wmcloader.class.title
                        class: Mapbender\CoreBundle\Element\Button
                        label: true
                        icon: iconWmcLoader
                        target: wmcloader
                        action: activate
                    wmc-list:
                        title: mb.wmc.wmclist.class.title
                        tooltip: mb.wmc.wmclist.class.title
                        class: Mapbender\WmcBundle\Element\WmcList
                        target: wmcloader                       
                content:
                    map:
                        title: mb.core.map.class.title
                        class: Mapbender\CoreBundle\Element\Map
                        layersets: [main]
                        srs: EPSG:25832
                        units: m
                        extents:
                            start: [361000,5619000,371150,5625000]
                            max: [-500000,4350000,1600000,6850000]
                        scales: [5000000,1000000,500000,100000,50000,25000,10000,7500,5000,2500,1000,500]
                        otherSrs: ["EPSG:25833","EPSG:31466","EPSG:31467","EPSG:3857","EPSG:4326"]
                    zoombar:
                        class: Mapbender\CoreBundle\Element\ZoomBar
                        target: map
                        components: ["pan","history","zoom_box","zoom_max","zoom_slider"]
                        stepsize: 50
                        stepbypixel: true
                        anchor: right-top
                        draggable: false
                    legend:
                        class: Mapbender\CoreBundle\Element\Legend
                        target: map
                        title: mb.core.legend.class.title
                        elementType: dialog
                        autoOpen: false
                        displayType: list
                        hideEmptyLayers: true
                        noLegend: "No legend available"
                        showWmsTitle: true
                        showLayerTitle: true
                        showGroupedLayerTitle: true
                    featureinfo:
                        class: Mapbender\CoreBundle\Element\FeatureInfo
                        title: mb.core.featureinfo.class.title
                        target: map
                        deactivateOnClose: false
                        onlyValid: true
                        type: dialog
                        displayType: tabs
                        autoActivate: false
                        printResult: true
                        showOriginal: true
                        width: 500
                        height: 500
                    wmsloader:
                        title: mb.wms.wmsloader.class.title
                        class: Mapbender\WmsBundle\Element\WmsLoader
                        target: map
                        autoOpen: false
                        defaultFormat: 'image/png'
                        defaultInfoFormat: 'text/html'
                        splitLayers: false
                    imageexport:
                        class: Mapbender\PrintBundle\Element\ImageExport
                        target: map
                        title: Image export
                    printclient:
                        title: mb.core.printclient.class.title
                        class: Mapbender\CoreBundle\Element\PrintClient
                        target: map
                        file_prefix: mapbender
                        templates:
                            - { template: a4portrait, label: A4 Portrait}
                            - { template: a4landscape, label: A4 Landscape}
                            - { template: a3portrait, label: A3 Portrait}
                            - { template: a3landscape, label: A3 Landscape}
                        scales: [500, 1000, 5000, 10000, 25000, 50000]
                        quality_levels:
                            - { dpi: 72 , label: Draft (72dpi)}
                            - { dpi: 288,  label: Document (288dpi)}
                        rotatable: true
                        legend: true
                        legend_default_behaviour: false
                        optional_fields:
                            title:
                                label: Title              # label of the optional field
                                options:                  #
                                    required: true        # true or false
                    lineruler:
                        title: mb.core.ruler.tag.line
                        tooltip: 'ruler'
                        class: Mapbender\CoreBundle\Element\Ruler
                        target: map
                        type: line
                    arearuler:
                        title: mb.core.ruler.tag.area
                        tooltip: 'area'
                        class: Mapbender\CoreBundle\Element\Ruler
                        target: map
                        type: area
                    scalebar:
                        class: Mapbender\CoreBundle\Element\ScaleBar
                        target: map
                        anchor: 'left-bottom'
                        position: ['10px', '10px']
                        maxWidth: 200
                        units: ['km']
                    layertreedialog:
                        title: mb.core.layertree.class.title
                        class: Mapbender\CoreBundle\Element\Layertree
                        target: map
                        type: dialog
                        autoOpen: false
                        showBaseSource: true
                        layerRemove: false
                        menu: []
                    overview:
                        title: mb.core.overview.class.title
                        class: Mapbender\CoreBundle\Element\Overview
                        tooltip: 'Overview'
                        target: map
                        layerset: overview
                        width: 200
                        height: 100
                        anchor: 'right-bottom'
                        position: ['0px', '0px']
                        maximized: true
                        fixed: false
                    scaledisplay:
                        title: mb.core.scaledisplay.class.title
                        class: Mapbender\CoreBundle\Element\ScaleDisplay
                        tooltip: Scale
                        target: map
                        anchor: left-top
                        scalePrefix: Scale
                        unitPrefix: true
                    poi:
                        title: mb.core.poi.class.title
                        class: Mapbender\CoreBundle\Element\POI
                        target: map
                        body: 'Please take a look at this POI'
                        useMailto: false
                    wmceditor:
                        title: mb.wmc.wmceditor.class.title
                        class: Mapbender\WmcBundle\Element\WmcEditor
                        tooltip: mb.wmc.wmceditor.class.title
                        target: map
                    wmcloader:
                        title: mb.wmc.wmcloader.class.title
                        class: Mapbender\WmcBundle\Element\WmcLoader
                        tooltip: mb.wmc.wmcloader.class.title
                        target: map                        
                        keepSources: null
                        components:
                            - wmcidloader
                            - wmclistloader
                            - wmcxmlloader
                        keepExtent: false
                sidepane:
                    layertree:
                        title: mb.core.layertree.class.title
                        class: Mapbender\CoreBundle\Element\Layertree
                        target: map
                        type: element
                        autoOpen: false
                        showBaseSource: true
                        layerRemove: true
                        menu: [opacity,zoomtolayer,metadata]
                    redlining:
                        title: mb.core.redlining.class.title
                        class: Mapbender\CoreBundle\Element\Redlining
                        target: map
                        geometrytypes:
                            - point
                            - line
                            - polygon
                            - text
                            - rectangle
                        display_type: element
                        auto_activate: false
                        deactivate_on_close: false
                    coordinatesutility:
                        title: mb.coordinatesutility.class.title
                        class: Mapbender\CoordinatesUtilityBundle\Element\CoordinatesUtility
                        type: element
                        target: map
                        srsList: []
                        addMapSrsList: true                        
                        zoomlevel: 6
                    html-about-mapbender:
                        title: 'About Mapbender'
                        class: Mapbender\CoreBundle\Element\HTMLElement
                        classes: html-element-inline
                        content: "<p>\r\nMapbender is an \r\n</p></br>\r\n<p>\r\n<a href=\"https://www.osgeo.org/projects/mapbender/\" target=\"_blank\"><img src=\"https://mapbender.org/sites/default/files/osgeo-project-cmyk.png\" alt=\"OSGeo Project\"  title=\"OSGeo Project\" width=\"100px\" /></a>\r\n</p></br>\r\n<p>\r\nFind out more about OSGeo at \r\n</br>\r\n<a href=\"https://osgeo.org\" target=\"_blank\">https://www.osgeo.org</a>\r\n</br>\r\n<a href=\"https://osgeo.org/projects/mapbender/\" target=\"_blank\">https://www.osgeo.org/projects/mapbender/</a>"

                footer:
                    activityindicator:
                        class: Mapbender\CoreBundle\Element\ActivityIndicator
                        title: mb.core.activityindicator.class.title
                        activityClass: mb-activity
                        ajaxActivityClass: mb-activity-ajax
                        tileActivityClass: mb-activity-tile
                    coordinates:
                        class: Mapbender\CoreBundle\Element\CoordinatesDisplay
                        title: mb.core.coordinates.class.title
                        tooltip: mb.core.coordinates.class.description
                        target: map
                        label: false
                        empty:  "x: - y: -"
                        prefix: "x: "
                        separator:  " y: "
                    srs:
                        class: Mapbender\CoreBundle\Element\SrsSelector
                        title: mb.core.srsselector.class.title
                        tooltip: mb.core.srsselector.class.description
                        label: false
                        target: map
                    scaleselector:
                        class: Mapbender\CoreBundle\Element\ScaleSelector
                        title: mb.core.scaleselector.class.title
                        tooltip: mb.core.scaleselector.class.description
                        label: false
                        target: map
                    copyrightButton:
                        title: © OpenStreetMap contributors
                        tooltip: © OpenStreetMap contributors
                        class: Mapbender\CoreBundle\Element\Button
                        label: true
                        click: https://www.openstreetmap.org/copyright
                    HTML:
                        title: HTML-powered by Mapbender
                        class: Mapbender\CoreBundle\Element\HTMLElement
                        content: '<span style="color: #6FB536; font-weight:bold">powered by Mapbender</span>'
                        classes: html-element-inline
